version: '3'
services:
  llm-datacraft-qa-generator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./qa_generator_outputs:/app/qa_generator_outputs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    command: poetry run uvicorn src.service:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=mydb
