version: '3'
services:
  llm-datacraft-qa-generator:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./qa_generator_outputs:/app/qa_generator_outputs
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: poetry run uvicorn src.service:app --host 0.0.0.0 --port 8000 --reload
