# fly.toml app configuration file generated for ragevals-lively-snowflake-5923-divine-bird-6466 on 2023-12-25T12:12:04-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ragevals-lively-snowflake-5923-divine-bird-6466"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096
